import "../src/styles/main.scss";
import { Inter } from 'next/font/google'
import {getServerSession} from "next-auth";
import {authOptions} from "@/src/lib/auth";
import {LoginButton} from "@/src/components/buttons";
import React from "react";
import {MainWrapper} from "@/src/wrappers/main-wrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  console.log(session);

  if(!session) {
    return (
        <html lang="en">
        <body className={inter.className}>
          <LoginButton />
        </body>
        </html>
    )
  }

  return (
    <html lang="en">
      <body className={inter.className}>
          <MainWrapper>
            {children}
          </MainWrapper>
      </body>
    </html>
  )
}
